const psd2htmlProjects = [
  {
    title: 'Sedona',
    preview: './data/projects/sedona/preview.jpg',
    id: 'sedona',
    description: '',
    keyWords: [
      'desktop-fluid 768-1200',
      'flex',
      'pixel perfect',
      'accessibility',
      'svg',
      'google map',
    ],
    source: 'htmlAcademy',
    web: './data/projects/sedona/index.html',
    year: '2018',
    kind: 'psd2html',
  },
  {
    title: 'Техномарт',
    preview: './data/projects/technomart/preview.jpg',
    id: 'technomart',
    description: '',
    keyWords: [
      'desktop-static',
      'flex',
      'pixel perfect',
      'css-sliders',
      'accessibility',
      'svg',
      'google map',
      'modals',
    ],
    source: 'htmlAcademy',
    web: './data/projects/technomart/index.html',
    github: 'https://github.com/d3x4r/technomart',
    year: '2018',
    kind: 'psd2html',
  },
  {
    title: 'Mishka',
    preview: './data/projects/mishka/preview.jpg',
    id: 'mishka',
    description: '',
    keyWords: [
      'adaptive',
      'gulp',
      'sass',
      'BEM',
      'flex',
      'pixel perfect',
      'modals',
      'retina',
      'webp',
      'google map',
    ],
    source: 'htmlAcademy',
    web: './data/projects/mishka/index.html',
    github: 'https://github.com/d3x4r/mishka',
    year: '2018',
    kind: 'psd2html',
  },
  {
    title: 'Brume',
    preview: './data/projects/brume/preview.jpg',
    id: 'brume',
    description: '',
    keyWords: ['adaptive', 'jquery', 'gulp', 'sass', 'BEM', 'flex', 'pixel perfect', 'webp'],
    source: 'personal',
    web: './data/projects/brume/index.html',
    github: 'https://github.com/d3x4r/Brume',
    year: '2019',
    kind: 'psd2html',
  },
  {
    title: 'Cakes',
    preview: './data/projects/cakes/preview.jpg',
    id: 'cakes',
    description: '',
    keyWords: ['adaptive', 'jquery', 'gulp', 'sass', 'BEM', 'flex', 'pixel perfect', 'webp'],
    source: 'personal',
    web: './data/projects/cakes/index.html',
    github: 'https://github.com/d3x4r/Cakes',
    year: '2019',
    kind: 'psd2html',
  },
];

const jsProjects = [
  {
    title: 'Keksobooking',
    preview: './data/projects/keksobooking/preview.jpg',
    id: 'keksobooking',
    description: '',
    keyWords: ['es5', 'ajax', 'form-validation', 'drag-n-drop'],
    source: 'htmlAcademy',
    web: './data/projects/keksobooking/index.html',
    github: 'https://github.com/d3x4r/keksobooking',
    year: '2018',
    kind: 'js',
  },
  {
    title: 'Brain games',
    preview: './data/projects/brain-games/preview.jpg',
    id: 'brainGames',
    description: '',
    keyWords: ['es6', 'babel', 'eslint', 'cli'],
    source: 'hexlet',
    web: '',
    github: 'https://github.com/d3x4r/Brain-Games',
    year: '2019',
    kind: 'js',
  },
  {
    title: 'Вычислитель отличий',
    preview: './data/projects/gendiff/preview.jpg',
    id: 'gendDiff',
    description: '',
    keyWords: ['es6', 'babel', 'eslint', 'cli', 'tree data'],
    source: 'hexlet',
    web: '',
    github: 'https://github.com/d3x4r/project-lvl2-s439',
    year: '2019',
    kind: 'js',
  },
  {
    title: 'Rss reader',
    preview: './data/projects/rss-reader/preview.jpg',
    id: 'rssReader',
    description: '',
    keyWords: ['webpack', 'bootstrap', 'ajax', 'DOM', 'validation', 'deploy'],
    source: 'hexlet',
    web: 'http://rss-r.surge.sh/',
    github: 'https://github.com/d3x4r/frontend-project-lvl3',
    year: '2019',
    kind: 'js',
  },
  {
    title: 'Список компаний',
    preview: './data/projects/company-list/preview.jpg',
    id: 'companyList',
    description: '',
    keyWords: ['vue', 'vue-cli', 'bootstrap', 'axios'],
    source: 'personal',
    web: 'http://company-ls.surge.sh',
    github: 'https://github.com/d3x4r/company-list',
    year: '2019',
    kind: 'js',
  },
];

const reactProjects = [
  {
    title: 'Projects overview',
    preview: './data/projects/projects-overview/preview.jpg',
    id: 'projectsOverview',
    description: '',
    keyWords: ['react', 'webpack', 'ajax', 'react-bootstrap'],
    source: 'personal',
    web: '',
    github: 'https://github.com/d3x4r/projects-overview',
    year: '2019',
    kind: 'js',
  },
];

export { psd2htmlProjects, jsProjects, reactProjects };
