const psd2htmlProjects = [
  {
    title: 'Sedona',
    preview: './projects/sedona/preview.jpg',
    id: 'sedona',
    description: '',
    keyWords: [
      'desktop-fluid 768-1200',
      'flex',
      'pixel perfect',
      'accessibility',
      'svg',
      'google map',
    ],
    source: 'htmlAcademy',
    web: './projects/sedona/index.html',
    year: '2018',
    kind: 'psd2html',
  },
  {
    title: 'Техномарт',
    preview: './projects/technomart/preview.jpg',
    id: 'technomart',
    description: '',
    keyWords: [
      'desktop-static',
      'flex',
      'pixel perfect',
      'css-sliders',
      'accessibility',
      'svg',
      'google map',
      'modals',
    ],
    source: 'htmlAcademy',
    web: './projects/technomart/index.html',
    github: 'https://github.com/d3x4r/technomart',
    year: '2018',
    kind: 'psd2html',
  },
  {
    title: 'Pink',
    preview: './projects/pink/preview.jpg',
    id: 'pink',
    description: '',
    keyWords: [
      'adaptive',
      'gulp',
      'sass',
      'BEM',
      'flex',
      'pixel perfect',
      'modals',
      'retina',
      'webp',
    ],
    source: 'htmlAcademy',
    web: './projects/pink/index.html',
    github: 'https://github.com/d3x4r/Pink',
    year: '2018',
    kind: 'psd2html',
  },
  {
    title: 'Mishka',
    preview: './projects/mishka/preview.jpg',
    id: 'mishka',
    description: '',
    keyWords: [
      'adaptive',
      'gulp',
      'sass',
      'BEM',
      'flex',
      'pixel perfect',
      'modals',
      'retina',
      'webp',
      'google map',
    ],
    source: 'htmlAcademy',
    web: './projects/mishka/index.html',
    github: 'https://github.com/d3x4r/mishka',
    year: '2018',
    kind: 'psd2html',
  },
  {
    title: 'Brume',
    preview: './projects/brume/preview.jpg',
    id: 'brume',
    description: '',
    keyWords: ['adaptive', 'jquery', 'gulp', 'sass', 'BEM', 'flex', 'pixel perfect', 'webp'],
    source: 'personal',
    web: './projects/brume/index.html',
    github: 'https://github.com/d3x4r/Brume',
    year: '2019',
    kind: 'psd2html',
  },
  {
    title: 'Cakes',
    preview: './projects/cakes/preview.jpg',
    id: 'cakes',
    description: '',
    keyWords: ['adaptive', 'jquery', 'gulp', 'sass', 'BEM', 'flex', 'pixel perfect', 'webp'],
    source: 'personal',
    web: './projects/cakes/index.html',
    github: 'https://github.com/d3x4r/Cakes',
    year: '2019',
    kind: 'psd2html',
  },
];

const jsProjects = [
  {
    title: 'Keksobooking',
    preview: './projects/keksobooking/preview.jpg',
    id: 'keksobooking',
    description: '',
    keyWords: ['es5', 'ajax', 'form-validation', 'drag-n-drop'],
    source: 'htmlAcademy',
    web: './projects/keksobooking/index.html',
    github: 'https://github.com/d3x4r/keksobooking',
    year: '2018',
    kind: 'js',
  },
  {
    title: 'Brain games',
    preview: './projects/brain-games/preview.jpg',
    id: 'brainGames',
    description: '',
    keyWords: ['es6', 'babel', 'eslint', 'cli'],
    source: 'hexlet',
    web: '',
    github: 'https://github.com/d3x4r/Brain-Games',
    year: '2019',
    kind: 'js',
  },
  {
    title: 'Вычислитель отличий',
    preview: './projects/gendiff/preview.jpg',
    id: 'gendDiff',
    description: '',
    keyWords: ['es6', 'babel', 'eslint', 'cli', 'tree data'],
    source: 'hexlet',
    web: '',
    github: 'https://github.com/d3x4r/project-lvl2-s439',
    year: '2019',
    kind: 'js',
  },
  {
    title: 'Rss reader',
    preview: './projects/rss-reader/preview.jpg',
    id: 'rssReader',
    description: '',
    keyWords: ['webpack', 'bootstrap', 'ajax', 'DOM', 'validation', 'deploy'],
    source: 'hexlet',
    web: 'http://rss-r.surge.sh/',
    github: 'https://github.com/d3x4r/frontend-project-lvl3',
    year: '2019',
    kind: 'js',
  },
  {
    title: 'Список компаний',
    preview: './projects/company-list/preview.jpg',
    id: 'companyList',
    description: '',
    keyWords: ['vue', 'vue-cli', 'bootstrap', 'axios'],
    source: 'personal',
    web: 'http://company-ls.surge.sh',
    github: 'https://github.com/d3x4r/company-list',
    year: '2019',
    kind: 'js',
  },
];

const reactProjects = [
  {
    title: 'Projects overview',
    preview: './projects/projects-overview/preview.jpg',
    id: 'projectsOverview',
    description: '',
    keyWords: ['react', 'webpack', 'ajax', 'react-bootstrap'],
    source: 'personal',
    web: '',
    github: 'https://github.com/d3x4r/projects-overview',
    year: '2019',
    kind: 'js',
  },
  {
    title: 'Hexagon',
    preview: './projects/hexagon/preview.png',
    id: 'hexagon',
    description: '',
    keyWords: ['react', 'form-validation', 'create-react-app', 'bootstrap'],
    source: 'personal',
    web: 'http://hxgn.surge.sh/',
    github: 'https://github.com/d3x4r/hexagon',
    year: '2020',
    kind: 'js',
  },
  {
    title: 'Todo app',
    preview: './projects/todo-app/preview.png',
    id: 'todo-app',
    description: '',
    keyWords: ['react', 'redux', 'create-react-app', 'material-ui'],
    source: 'personal',
    web: 'http://t0d0-app.surge.sh/',
    github: 'https://github.com/d3x4r/todo-app',
    year: '2020',
    kind: 'js',
  },
  {
    title: 'StarWars DB',
    preview: './projects/star-wars-db/preview.jpg',
    id: 'star-wars-db',
    description: '',
    keyWords: ['react', 'react-router', 'fetch', 'bootstrap', 'create-react-app'],
    source: 'personal',
    web: 'http://star-w-db.surge.sh/',
    github: 'https://github.com/d3x4r/StarWarsDB',
    year: '2020',
    kind: 'js',
  },
  {
    title: 'Re-store',
    preview: './projects/re-store/preview.jpg',
    id: 're-store',
    description: '',
    keyWords: [
      'react',
      'redux',
      'redux-thunk',
      'react-router',
      'bootstrap',
      'create-react-app',
      'airbnb-eslint-config',
    ],
    source: 'personal',
    web: 'http://re-restore.surge.sh/',
    github: 'https://github.com/d3x4r/re-store',
    year: '2020',
    kind: 'js',
  },
];

export { psd2htmlProjects, jsProjects, reactProjects };
